import Logo from '@/components/Image/moderneye.png';
import offerImgOne from '@/components/Image/Navbar-img1.webp';
import offerImgTwo from '@/components/Image/Navbar-img2.webp';
import offerImgThree from '@/components/Image/Navbar-img3.webp';
import HomeImgOne from '@/components/Image/home-img1.webp';
import HomeImgTwo from '@/components/Image/home-img2.webp';
import HomeImgThree from '@/components/Image/home-img3.webp';
import HomeImgFour from '@/components/Image/home-img4.webp';
import HomeImgFive from '@/components/Image/home-img5.webp';
import HomeBanner from '@/components/Image/Home-banner.jpg';
import SwiperImgOne from '@/components/Image/SwiperImgOne.webp';
import SwiperImgTwo from '@/components/Image/SwiperImgTwo.webp';
import SwiperImgThree from '@/components/Image/SwiperImgThree.webp';
import SwiperImgFour from '@/components/Image/SwiperImgFour.webp';
import SwiperImgFive from '@/components/Image/SwiperImgFive.webp';
import SwiperImgSix from '@/components/Image/SwiperImgSix.webp';
import Round from '@/components/Image/Round.webp';
import Aviator from '@/components/Image/Aviator.webp';
import Airflix from '@/components/Image/airflex.webp';
import Blend from '@/components/Image/blend.webp';
import Clipon from '@/components/Image/clipon.webp';
import Cateye from '@/components/Image/cateeye.webp';
import Clubmaster from '@/components/Image/clubmaster.webp';
import Clubmaster2 from '@/components/Image/clubmaster2.webp';
import Clubmaster6 from '@/components/Image/Clubmaster6.webp';
import Clubmaster3 from '@/components/Image/clubmaster4.webp';
import Clubmaster4 from '@/components/Image/clubmaster3.webp';
import Trans from '@/components/Image/trans.webp';
import cardSwiperImg1 from '@/components/Image/cardSwiperImg1.jpg';
import cardSwiperImg2 from '@/components/Image/cardSwiperImg2.jpg';
import cardSwiperImg3 from '@/components/Image/swiperImg3.jpg';
import cardSwiperImg4 from '@/components/Image/swiperImg4.jpg';
import Banner from '@/components/Image/banner.jpg'
import secondBanner from '@/components/Image/secondBanner.jpg'
import secondBanner2 from '@/components/Image/secondBanner2.jpg'
import Facebook from '@/components/Image/facebook.png'
import Insta from '@/components/Image/instagram.png'
import Twitter from '@/components/Image/twitter.png'
import LinkedIn from '@/components/Image/linkedin.png'
import Hexa from '@/components/Image/hexa.jpg';
import square from '@/components/Image/square.jpg';
import clibmaster from '@/components/Image/clibmaster.jpg';
import wayfarer from '@/components/Image/wayfarer.jpg';
import Rectangle from '@/components/Image/rectangle.jpg';
import MenAviator from '@/components/Image/men aviator.jpg';
import adminLogo from '@/components/Image/adminLogo.svg'

export {Logo,adminLogo,Hexa,wayfarer,square,clibmaster,Rectangle,MenAviator,Insta,LinkedIn,Twitter,Facebook,Airflix,Banner,secondBanner2,secondBanner,Clubmaster6,Clubmaster3,Clubmaster4,Clubmaster2,Round,Blend,Aviator,Clipon,cardSwiperImg4,cardSwiperImg3,cardSwiperImg2,cardSwiperImg1,Cateye,Trans,Clubmaster,SwiperImgFour,SwiperImgThree,SwiperImgSix , SwiperImgOne , SwiperImgFive, SwiperImgTwo , offerImgOne,offerImgThree,HomeBanner,offerImgTwo,HomeImgOne,HomeImgThree,HomeImgTwo,HomeImgFive,HomeImgFour};